
export const LOADING_APP = 'LOADING_APP'
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED'
export const SET_TOKEN = 'SET_TOKEN'
export const PROJECTS_LOADED = 'PROJECTS_LOADED'
export const SPACES_LOADED = 'SPACES_LOADED'
export const BUILD_SPACES_HIERARCHY = 'BUILD_SPACES_HIERARCHY'


export const LOADING_LAYOUT = 'LOADING_LAYOUT'
export const LAYOUTS_LOADED = 'LAYOUTS_LOADED'
export const EVENTS_LOADED = 'EVENTS_LOADED'
export const DEVICES_LOADED = 'DEVICES_LOADED'
export const DRIVERS_LOADED = 'DRIVERS_LOADED'
export const GATEWAYS_LOADED = 'GATEWAYS_LOADED'
export const MACROS_LOADED = 'MACROS_LOADED'
export const COMPUTING_LAYOUT_ANALYSIS = 'COMPUTING_LAYOUT_ANALYSIS'
export const COMPUTING_LAYOUT_PREVIEW = 'COMPUTE_LAYOUT_PREVIEW'

export const INVALID_TOKEN = 'INVALID_TOKEN'
export const SERVER_ERROR = 'SERVER_ERROR'

export const SET_ACTIVE_PROJECT = 'SET_ACTIVE_PROJECT'
export const SET_ACTIVE_LAYOUT = 'SET_ACTIVE_LAYOUT'
export const SET_ACTIVE_SPACE = 'SET_ACTIVE_SPACE'